name: sr_edu_care
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  go_router: ^17.0.1
  flutter_spinkit: ^5.2.2
  any_image_view: ^1.9.0
  dio: ^5.9.0
  shared_preferences: ^2.5.4
  flutter_dotenv: ^6.0.0
  fpdart: ^1.2.0
  get_it: ^9.2.0
  flutter_easyloading: ^3.0.5
  fluttertoast: ^9.0.0
  jwt_decoder: ^2.0.1
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - .env
